version: '3'

services: 
    script:
        build: .
        image: cons_esp_habana
        command: bash -c "python main.py"
        container_name: cons_esp_habana
        volumes:
        - .:/cons_esp_habana
        ports:
        - "8000:8000"
