version: '3'

services: 
    script:
        build: .
        image: spanish_consular_procedure
        command: bash -c "python main.py"
        container_name: spanish_consular_procedure
        volumes:
        - .:/spanish_consular_procedure
        ports:
        - "8000:8000"
